package enums;

public enum Skill {
    COMMUNICATION,
    LEADERSHIP,
    CREATIVITY,
    TEAMWORK,
    ADAPTABILITY,
    CRITICAL_THINKING,
    NEGOTIATION,
    SELF_MOTIVATION,
    STRESS_MANAGEMENT,
    TECHNICAL_KNOWLEDGE,
    FAST_LEARNING,
    PROBLEM_SOLVING,
    TIME_MANAGEMENT,
    PRESENTATION_SKILLS,
    DECISION_MAKING,
    PROJECT_MANAGEMENT,
    TEACHING,
    RESEARCH,
    MENTORING,
    NETWORKING,
    FINANCIAL_MANAGEMENT,
    ENGLISH
}
